/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employeeManagementSystemGUI;
import eqms.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
/**
 *
 * @author amro
 */
public class addEmployeeGUI extends javax.swing.JFrame {
    private ArrayList<EmployeeSkill>employeeSkills;
    private ArrayList<Qualification>qualifications; 
    private DefaultListModel employeeSkillsListModel;
    private DefaultListModel qualificationsListModel;
    
    public addEmployeeGUI() {
        initComponents();
        
        employeeSkills = new ArrayList<EmployeeSkill>();
        qualifications = new ArrayList<Qualification>();
        employeeSkillsListModel = new DefaultListModel();
        qualificationsListModel = new DefaultListModel();
        DefaultListModel temp1 = new DefaultListModel();
        ArrayList<Qualification>qualifications = AddEmployee.retrieveQualifications();
        for(int i = 0; i < qualifications.size(); ++i){
            Integer number = i+1;
            temp1.addElement(number.toString()+ "- " + AddEmployee.retrieveQualification(i).showQualification());
        }        
        qualificationsList.setModel(temp1);
        DefaultListModel temp2 = new DefaultListModel();
        ArrayList<Skill>skills = AddEmployee.retrieveSkills();
        for(int i = 0; i < skills.size(); ++i){
            Integer number = i+1;
            temp2.addElement(number.toString()+ "- " + skills.get(i).showSkill());
        }        
        skillsList.setModel(temp2);
        DefaultListModel temp3 = new DefaultListModel();
        ArrayList<Insurance>insurance = AddEmployee.retrieveInsurances();
        for(int i = 0; i < insurance.size(); ++i){
            Integer number = i+1;
            temp3.addElement(number.toString()+ "- " +  AddEmployee.retrieveInsurance(number).showPackage());
        }        
        insurancePackagesList.setModel(temp3);
        DefaultListModel temp4 = new DefaultListModel();
        ArrayList<JobTitle>jobTitle = AddEmployee.retrieveJobTitles();
        for(int i = 0; i < jobTitle.size(); ++i){
            Integer number = i+1;
            temp4.addElement(number.toString()+ "- " + AddEmployee.retrieveJobTitle(number).getJobTitle());
        }        
        jobTitlesList.setModel(temp4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane9 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        ssnInput = new javax.swing.JTextField();
        addedSkillsLabel = new javax.swing.JLabel();
        enterPackageLabel = new javax.swing.JLabel();
        genderInput = new javax.swing.JTextField();
        addSkillButton = new javax.swing.JButton();
        genderLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        ssnLabel = new javax.swing.JLabel();
        dateOfBirthInput = new javax.swing.JTextField();
        enterPackageInput = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        addedSkillsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        qualificationsList = new javax.swing.JList<>();
        emailLabel = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        skillsList = new javax.swing.JList<>();
        enterJobTitleInput = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        enterSkillLabel = new javax.swing.JLabel();
        enterQualificationLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        enterSkillInput = new javax.swing.JTextField();
        employmentDateInput = new javax.swing.JTextField();
        addedQualificationsLabel = new javax.swing.JLabel();
        jobTitlesLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addQualifiicationButton = new javax.swing.JButton();
        enterQualificationInput = new javax.swing.JTextField();
        insurancePackagesLabel = new javax.swing.JLabel();
        dateOfBirthLabel = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        skillsLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        insurancePackagesList = new javax.swing.JList<>();
        qualificationsLabel = new javax.swing.JLabel();
        enterJobTitleLabel = new javax.swing.JLabel();
        phoneInput = new javax.swing.JTextField();
        employmentDateLabel = new javax.swing.JLabel();
        emailInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        jScrollPane4 = new javax.swing.JScrollPane();
        addedQualificationsList = new javax.swing.JList<>();
        addressInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        jobTitlesList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1083, 2300));

        jPanel1.setPreferredSize(new java.awt.Dimension(1081, 3000));

        ssnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnInputActionPerformed(evt);
            }
        });

        addedSkillsLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addedSkillsLabel.setText("Added skills");

        enterPackageLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterPackageLabel.setText("Enter package number");

        addSkillButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addSkillButton.setText("Add");
        addSkillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSkillButtonActionPerformed(evt);
            }
        });

        genderLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        genderLabel.setText("Gender:");

        addressLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addressLabel.setText("Address:");

        ssnLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ssnLabel.setText("Ssn:");

        jScrollPane6.setViewportView(addedSkillsList);

        jScrollPane3.setViewportView(qualificationsList);

        emailLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        emailLabel.setText("Email:");

        header.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        header.setText("Employee Management System");

        jScrollPane5.setViewportView(skillsList);

        passwordLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passwordLabel.setText("Password:");

        enterSkillLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterSkillLabel.setText("Enter skill number");

        enterQualificationLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterQualificationLabel.setText("Enter qualification number");

        phoneLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phoneLabel.setText("Phone:");

        enterSkillInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterSkillInputActionPerformed(evt);
            }
        });

        addedQualificationsLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addedQualificationsLabel.setText("Added qualifications");

        jobTitlesLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jobTitlesLabel.setText("Job titles");

        nameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameLabel.setText("Name:");

        addQualifiicationButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addQualifiicationButton.setText("Add");
        addQualifiicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQualifiicationButtonActionPerformed(evt);
            }
        });

        insurancePackagesLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        insurancePackagesLabel.setText("Insurance packages");

        dateOfBirthLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dateOfBirthLabel.setText("Date of birth (DD-MM-YYYY):");

        skillsLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        skillsLabel.setText("Skills");

        jScrollPane7.setViewportView(insurancePackagesList);

        qualificationsLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        qualificationsLabel.setText("Qualifications");

        enterJobTitleLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enterJobTitleLabel.setText("Enter job title number");

        employmentDateLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        employmentDateLabel.setText("Employment date (DD-MM-YYYY):");

        jScrollPane4.setViewportView(addedQualificationsList);

        submitButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jScrollPane10.setViewportView(jobTitlesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(362, 362, 362))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ssnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(834, 834, 834)
                        .addComponent(ssnInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(818, 818, 818)
                        .addComponent(nameInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(786, 786, 786)
                        .addComponent(passwordInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(821, 821, 821)
                        .addComponent(emailInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(800, 800, 800)
                        .addComponent(addressInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(813, 813, 813)
                        .addComponent(phoneInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(805, 805, 805)
                        .addComponent(genderInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(767, 767, 767)
                        .addComponent(dateOfBirthInput))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(employmentDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(727, 727, 727)
                        .addComponent(employmentDateInput)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(qualificationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(473, 473, 473))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addedQualificationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(609, 609, 609)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterQualificationInput)
                                    .addComponent(enterQualificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(606, 606, 606)
                                .addComponent(addQualifiicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(25, 25, 25)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(skillsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(566, 566, 566))
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(addedSkillsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(617, 617, 617)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(enterSkillLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(enterSkillInput)
                                    .addComponent(addSkillButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(insurancePackagesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(486, 486, 486))
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(enterJobTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(476, 476, 476))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(enterJobTitleInput)
                        .addGap(476, 476, 476))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(517, 517, 517))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jobTitlesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(530, 530, 530))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(386, 386, 386)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterPackageInput)
                            .addComponent(enterPackageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(476, 476, 476)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ssnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ssnInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(nameInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(passwordInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(emailInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(addressInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(phoneInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(genderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(genderInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateOfBirthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(dateOfBirthInput)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employmentDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(employmentDateInput)
                        .addGap(4, 4, 4)))
                .addGap(43, 43, 43)
                .addComponent(qualificationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addedQualificationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(enterQualificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(enterQualificationInput, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                        .addGap(28, 28, 28)
                        .addComponent(addQualifiicationButton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                        .addGap(5, 5, 5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skillsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addedSkillsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(enterSkillLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(enterSkillInput, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(addSkillButton, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insurancePackagesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterPackageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(enterPackageInput, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(jobTitlesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterJobTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(enterJobTitleInput)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1007, 1007, 1007))
        );

        jScrollPane9.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 2053, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterSkillInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterSkillInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterSkillInputActionPerformed

    private void ssnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnInputActionPerformed

    private void addSkillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSkillButtonActionPerformed
        int skillNumber = Integer.valueOf(enterSkillInput.getText());
        enterSkillInput.setText("");
        
        ArrayList<Skill>skills = AddEmployee.retrieveSkills();
        
        if(skillNumber > skills.size()){
            JOptionPane.showMessageDialog(null, "Invalid input\nPlease, enter a number between 1 and " + skills.size());
        }
        else{
            employeeSkills.add(new EmployeeSkill(skills.get(skillNumber - 1)));
            employeeSkillsListModel.addElement(skills.get(skillNumber - 1).showSkill());
            addedSkillsList.setModel(employeeSkillsListModel);
        }
    }//GEN-LAST:event_addSkillButtonActionPerformed

    private void addQualifiicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQualifiicationButtonActionPerformed
        int qualificationNumber = Integer.valueOf(enterQualificationInput.getText());
        enterQualificationInput.setText("");
        
        ArrayList<Qualification>qualifications = AddEmployee.retrieveQualifications();
        
        if(qualificationNumber > qualifications.size()){
            JOptionPane.showMessageDialog(null, "Invalid input\nPlease, enter a number between 1 and " + qualifications.size());
        }
        else{
            qualifications.add(AddEmployee.retrieveQualification(qualificationNumber - 1));
            qualificationsListModel.addElement(qualifications.get(qualificationNumber - 1).showQualification());
            addedQualificationsList.setModel(qualificationsListModel);
        }
    }//GEN-LAST:event_addQualifiicationButtonActionPerformed
    
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        long ssn = Long.valueOf(ssnInput.getText());
        String name = nameInput.getText();
        char tempPassword[] = passwordInput.getPassword();
        String password = new String(tempPassword);
        String email = emailInput.getText();
        String address = addressInput.getText();
        long phoneNumber = Long.valueOf(phoneInput.getText());
        String gender = genderInput.getText();
        String dateOfBirth = dateOfBirthInput.getText();
        String employmentDate = employmentDateInput.getText();
        int packageNumber = Integer.valueOf(enterPackageInput.getText());
        int jobTitleNumber = Integer.valueOf(enterJobTitleInput.getText());
        
        Employee newEmployee = new Employee(ssn, name, address, email, password, phoneNumber, gender, employmentDate, dateOfBirth, employeeSkills, qualifications, new ArrayList<Achievement>(), AddEmployee.retrieveInsurance(packageNumber), AddEmployee.retrieveJobTitle(jobTitleNumber));

        while(AddEmployee.sendEmployeeInfo(newEmployee) != true){
            JOptionPane.showMessageDialog(null, "Invalid Ssn");
            long newSsn = Long.valueOf(JOptionPane.showInputDialog(null, "Please enter another Ssn"));
            newEmployee.setSsn(newSsn);
        }
        JOptionPane.showMessageDialog(null, "Emplyee has been added successfully");
        this.dispose();
        new addEmployeeGUI().setVisible(true);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addEmployeeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addEmployeeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQualifiicationButton;
    private javax.swing.JButton addSkillButton;
    private javax.swing.JLabel addedQualificationsLabel;
    private javax.swing.JList<String> addedQualificationsList;
    private javax.swing.JLabel addedSkillsLabel;
    private javax.swing.JList<String> addedSkillsList;
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField dateOfBirthInput;
    private javax.swing.JLabel dateOfBirthLabel;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField employmentDateInput;
    private javax.swing.JLabel employmentDateLabel;
    private javax.swing.JTextField enterJobTitleInput;
    private javax.swing.JLabel enterJobTitleLabel;
    private javax.swing.JTextField enterPackageInput;
    private javax.swing.JLabel enterPackageLabel;
    private javax.swing.JTextField enterQualificationInput;
    private javax.swing.JLabel enterQualificationLabel;
    private javax.swing.JTextField enterSkillInput;
    private javax.swing.JLabel enterSkillLabel;
    private javax.swing.JTextField genderInput;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel header;
    private javax.swing.JLabel insurancePackagesLabel;
    private javax.swing.JList<String> insurancePackagesList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel jobTitlesLabel;
    private javax.swing.JList<String> jobTitlesList;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phoneInput;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel qualificationsLabel;
    private javax.swing.JList<String> qualificationsList;
    private javax.swing.JLabel skillsLabel;
    private javax.swing.JList<String> skillsList;
    private javax.swing.JTextField ssnInput;
    private javax.swing.JLabel ssnLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
